import * as https from 'https';

const BASE_URL = 'https://plantmainthq.com';

// A sample of the newly generated URLs to test (using .html as generated by the build script)
const urlsToTest = [
  `${BASE_URL}/`,
  `${BASE_URL}/software/ibm-maximo.html`, 
  `${BASE_URL}/software/maintainx.html`, 
  `${BASE_URL}/best-cmms-for-manufacturing.html`, 
  `${BASE_URL}/compare/maintainx-vs-limble-cmms.html` 
];

console.log(`\n🔍 Verifying live URLs on ${BASE_URL}...\n`);

let pending = urlsToTest.length;
let successCount = 0;

urlsToTest.forEach(url => {
  https.get(url, (res) => {
    if (res.statusCode === 200) {
      console.log(`✅ SUCCESS (200): ${url}`);
      successCount++;
    } else {
      console.log(`❌ FAILED (${res.statusCode}): ${url}`);
    }
    
    pending--;
    if (pending === 0) {
      console.log(`\n📊 Verification Complete: ${successCount}/${urlsToTest.length} pages are live and returning 200 OK.`);
      
      if (successCount !== urlsToTest.length) {
        console.log(`\n⚠️ NOTE: If pages are failing (404), it means Cloudflare is not serving the updated 'dist' folder.`);
        console.log(`Please log into your Cloudflare Dashboard -> Pages -> Settings -> Builds & Deployments.`);
        console.log(`Ensure your 'Build output directory' is set exactly to: dist`);
      }
    }
  }).on('error', (e) => {
    console.error(`🚨 ERROR fetching ${url}: ${e.message}`);
    pending--;
  });
});
